### ISSUE TITLE
Script for moving money from bots to wallet

### ISSUE THREAD

**Issue by slundqui** [delvtech/elf-simulations#1025]
There exists a use case where we're done with bots, and want to use the money for click trading again. Provide a script that moves money from bots to wallet. This also allows a generic solution on how to close a set of bots in favor of another.

**Comment by dpaiton** [comment]
Would be nice if this script was bi-directional (so I can quickly transfer money TO or FROM a specific bot wallet). Really, generalizing it to transfer money TO address & FROM address and make it have a nice CLI flag for auto-transferring the full balance would be best IMO.

**Comment by dpaiton** [comment]
closing this as not-planned -- one can use metamask to do it and there doesn't seem to be a need to automate. It's also not needed for postprocessing & competition analysis.
