### ISSUE TITLE
Add geometric brownian motion generator for simulating vault yield over time

### ISSUE THREAD

**Issue by jalextowle** [delvtech/elf-simulations#104]
It's questionable whether or not the `stochastic` package is well-maintained and the logic is simple. Having said this, the implementation details are not going to change over time except to adapt to library changes, so this is not a maintenance-heavy project.

**Comment by dpaiton** [comment]
We should use add the geometric brownian motion generator to our core codebase with a test, and then remove the `stochastic` dependency

**Comment by dpaiton** [comment]
The `stochastic` dependency has been removed, but we still need to add back a geometric brownian motion generator for vault apr (variable apr) simulations.

**Comment by dpaiton** [comment]
Closing; we can spin this back up once we finish setting up the new simulation repo
