### ISSUE TITLE
Update test_calc_in_given_out test comments to match test_calc_out_given_in

### ISSUE THREAD

**Issue by sentilesdal** [delvtech/elf-simulations#222]
Use this colab to update the in_given_out tests to match the out_given_in tests as they are much better commented.  

https://colab.research.google.com/drive/197RbisxFR8W0azyz8ugJo-PAwrF0k2RJ#scrollTo=S3CBdg0UXH8j

**Comment by dpaiton** [comment]
Closing since the parity effort is moving to the Rust repo
