### ISSUE TITLE
Find cause of random bot crash conditions

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#325]
while working on https://github.com/element-fi/elf-simulations/pull/321 I noticed the random bot crashes in certain situations only:
- terms to maturity of >= 364
- `trade_chance` = 1
not sure why but these are causing problems in the smart contract execution, returning `ape.exceptions.ContractLogicError: Transaction failed.`

**Comment by wakamex** [comment]
We were keeping the smart contract term at 365 days even when varying the python term. Changing it to match makes it crash. It runs when the solidity term is 2+ days longer than the python term (8 vs. 10 days, 363 vs. 365 days).

```
starting values for share_price:
 sim=1.0
 sol=0.48806958202484735
starting values for fixed_apr:
 sim=0.04999999999999317,
 sol=0.05
```
![output](https://user-images.githubusercontent.com/16990562/230477423-d8818aee-e58c-441d-8efe-01a7c9ec47d7.png)

**Comment by dpaiton** [comment]
Closing, seems like bots are fine now.
