### ISSUE TITLE
Find cause of discrepancy w/ smart contracts in bots on solidity

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#326]
LP total supply still has a few differences, which I think arise from the different units of `trade_amount` not being accounted for (will fix) but the difference in reported share price is much larger.
![image](https://user-images.githubusercontent.com/16990562/230291825-c5f536fa-8145-4304-bb3e-1dfef3cbf284.png)

Thinking something with the treatment of accrual for share price in the mocked hyperdrive contracts may be the issue. Looking at this: https://github.com/element-fi/hyperdrive/pull/161/files#diff-4f6b529ddab10dfecb835ad8d23c24644c993a24b4ec6f05f90c709179bc390b

**Comment by dpaiton** [comment]
@wakamex can you flag this task in discord, per our visibility request last week

**Comment by dpaiton** [comment]
Assume this is resolved (+1 mo old)
