### ISSUE TITLE
Transformers: getPoolInfo, getPoolConfig --> MarketState

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#391]

**Comment by wakamex** [comment]
I query the hyperdrive contract's `getPoolInfo` and `getPoolConfig`.
I use the config's `positionDuration` to encode the asset id of withdrawal shares, which i think query using `balanceOf`.
I build `MarketState` by using its constructor in `elfpy.markets.hyperdrive`

**Comment by wakamex** [comment]
committed example here, but tests not passing yet (ran out of time) https://github.com/delvtech/elf-simulations/commit/f15a96258ab208f8c53c5b2135d29f8a62ab468d

**Comment by dpaiton** [comment]
Making a new issue for tests #542
