### ISSUE TITLE
Transformers: tx_receipt --> WalletDelta

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#392]
calls some solidity func on an agent address, gets elfpy wallet back out

**Comment by wakamex** [comment]
committed example here, but tests not passing yet (ran out of time) https://github.com/delvtech/elf-simulations/commit/f15a96258ab208f8c53c5b2135d29f8a62ab468d

**Comment by dpaiton** [comment]
Initial pass achieved by #412
