### ISSUE TITLE
Transformers: getPoolInfo --> market_deltas

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#395]
function should take in contract address & existing market state, and then use getPoolInfo to convert to market_deltas

**Comment by wakamex** [comment]
committed example here, but tests not passing yet (ran out of time) https://github.com/delvtech/elf-simulations/commit/f15a96258ab208f8c53c5b2135d29f8a62ab468d

**Comment by dpaiton** [comment]
Skipping in favor of calling [get_hyperdrive_market](https://github.com/delvtech/elf-simulations/blob/7ae64e72dce71a9155b02530c31fcb17e158d4ab/elfpy/hyperdrive_interface/hyperdrive_interface.py#L193) each time. This would be nice to have down the road, we can accomplish it by copying the behavior for computing agent wallet deltas.
