### ISSUE TITLE
Transformers: (py) trade_details --> abi_call

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#397]

**Comment by wakamex** [comment]
atomic level functions that anyone can call for arbitrary use.

here we use trade details tailored to evm_bots, which could be generalized for this purpose:
https://github.com/delvtech/elf-simulations/blob/9b7c228b00a604f8abc4310d0fc7c9915d4902c7/elfpy/utils/apeworx_integrations.py#LL614C9-L614C9
