### ISSUE TITLE
Fixtures: create-agent

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#404]
two modes:
* agent (`ape.accounts.test_accounts.generate_test_account()`) that doesn't have real money
* agent that has a real test-net account & money in it

**Comment by wakamex** [comment]
are you looking to do something at all like this? @sentilesdal 
https://github.com/delvtech/elf-simulations/blob/4616574aeac090d3a00a191db2246edeb306157d/examples/evm_bots.py#LL372C18-L372C18

**Comment by dpaiton** [comment]
Resolved by #505
