### ISSUE TITLE
Fixtures: create provider

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#405]
`ape.networks.parse_network_choice("ethereum:local:foundry").__enter__()`

Two modes:
* on test-net (goerli or whatever we make)
* on local simulated chain

**Comment by wakamex** [comment]
I've generalized my call to create provider here, but I'm not sure if it's useful to @sentilesdal since he'll probably just be using the built-in `TestProvider`
https://github.com/delvtech/elf-simulations/blob/488c8ea3fc3d1b7d187ffb2cc95dbc7a488a166e/examples/evm_bots.py#L667

**Comment by wakamex** [comment]
this is overdue!!!! can I get an update @sentilesdal !!

**Comment by sentilesdal** [comment]
This is fnished in #505

**Comment by ryangoree** [comment]
> This is fnished in #505

Closing and moving to Done
