### ISSUE TITLE
fix get_max_short and get_max_long

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#440]
fix a few problems with get_max_short:
- innacuracy previous noticed (#288) 
- causing crash when running bots on goerlit testnet

**Comment by dpaiton** [comment]
New Hyperdrive sol `calculateMaxLong` methodology here: https://github.com/delvtech/hyperdrive/pull/302

**Comment by wakamex** [comment]
closing for now, not sure if it has any relevance in light of the new implementation. saving to my fork to review later, if there's any need.

**Comment by dpaiton** [comment]
@sentilesdal the `calculate_max_short` function has in the docstring:
```
    Returns
    -------
    FixedPoint
        The maximum amount of shares that can be used to open shorts.
```
and then returns
```
    # The optimal bond reserves imply a maximum short of dy = y - y0.
    return optimal_bond_reserves - bond_reserves
```

2 things:
1. do you think it would be better to return a base_amount and bond_amount like `calculate_max_long` does?
2. the docstring says "shares" but it looks like the returned unit is "bonds"
