### ISSUE TITLE
crash-reporting: human-readable crash report on revert

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#479]
Crash report should have pool info, pool config, trade info and be able to be directly copied into a GH issue bug report.

**Comment by slundqui** [comment]
Removing functionality in https://github.com/delvtech/elf-simulations/pull/807 until ready to implement again.

Change of interest:
lib/chainsync/chainsync/hyperdrive/crash_report.py

**Comment by dpaiton** [comment]
Resolved in https://github.com/delvtech/elf-simulations/pull/1012
