### ISSUE TITLE
lint docstrings

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#501]
lets you know when you missed a variable which seems valuable when working with lots of inputs and outputs:
"base_instance" missing in parameter documentation

should help maintain docstrings up-to-date with changes to the code. I've seen a lot of docstrings fall behind, which renders them useless.

unfortunately it doesn't check whether you used a totally different description for the same variable name in another docstring.

**Comment by dpaiton** [comment]
We can also test the docstrings via https://docs.python.org/3/library/doctest.html

This would be a great addition!

**Comment by wakamex** [comment]
all #500 does is make pylint complain if you don't document parameters, return and yield variables in your docstring
I tested that out while working on evm_bots cus it had a ton of docstrings
forcing myself to put every single parameter and return variable in the docstring was a bit annoying and resulted in boilerplate like this:
```
action_list : list[types.Trade]
    list of actions to take
```
do we want to say "not every function needs parameters / return variables in its docstring" ? if so, will close that PR

**Comment by wakamex** [comment]
docstrings aren't required for private functions, so #500 still makes sense, I think. then we can just use private functions for functions where adding a docstring wouldn't be useful.

> by default docstrings of private and magic methods are not checked.
<https://github.com/pylint-dev/pylint/blob/main/pylint/extensions/docparams.rst>

**Comment by dpaiton** [comment]
Created in https://github.com/delvtech/elf-simulations/pull/694 but we turned it off for the trading competition. We will turn it back on next week.
