### ISSUE TITLE
write tests for evm_bots

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#504]
should include:

- checks for all input combos
- possibly run and check for output

**Comment by wakamex** [comment]
kind of started with transformers tests (not working yet) doing evm_bots-like behavior https://github.com/delvtech/elf-simulations/commit/f15a96258ab208f8c53c5b2135d29f8a62ab468d

**Comment by dpaiton** [comment]
EVM bots is deprecated
