### ISSUE TITLE
need more fields in historical data to create elfpy market

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#530]
# VARIABLES WE HAVE
lp_total_supply
share_reserves
bond_reserves
share_price
longs_outstanding
shorts_outstanding
long_average_maturity_time
short_average_maturity_time
long_base_volume
short_base_volume

# VARIABLES WE DONT HAVE
- some of these currently exist, but will be removed as we improve parity (marked by `*`)
- some of these are in GetPoolInfo, just need to be retrieved (marked by `i`)
- some of these are in GetPoolConfig, just need to be retrieved (marked by `c`)

init_share_price`c`
base_buffer`*`
bond_buffer`*`
variable_apr`(need to ask to have it added to GetPoolInfo)`
curve_fee_multiple`c`
flat_fee_multiple`c`
governance_fee_multiple`c`
gov_fees_accrued
position_duration`c`
checkpoint_duration`c`
checkpoint_duration_days
time_stretch`c`
total_supply_longs
total_supply_shorts
total_supply_withdraw_shares
withdraw_shares_ready_to_withdraw`i`
withdraw_capital`*`
withdraw_interest`*`
new variable: withdrawalSharesProceeds

**Comment by dpaiton** [comment]
partially address by #540

**Comment by dpaiton** [comment]
This is resolved in chainsync.
