### ISSUE TITLE
crash-reporting: dump anvil full state when bots go down

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#541]
One can use `anvil_dumpState` ([docs](https://book.getfoundry.sh/reference/anvil/#custom-methods)) to dump the state to a hex string, and then `anvil_loadState` to pull them back up. This will be useful for debugging when bots crash. Assuming a flag is set, we want to save the state to a file whenever the bots crash and then write the appropriate script to spin Anvil back up from that state for debugging. This second part should probably happen outside of Docker; i.e. running a local anvil instance on our machines so that we can quickly get into a debug state.

**Comment by wakamex** [comment]
example of making arbitrary anvil call from ape:
`automine = provider._make_request("anvil_getAutomine", parameters={}) # pylint: disable=protected-access`
then after getting a PR to explicitly add the command: `provider.auto_mine`
anvil command reference is here: [https://book.getfoundry.sh/reference/anvil/](https://book.getfoundry.sh/reference/anvil/)
which includes these, that I haven't tried yet:
```
anvil_dumpState Returns a hex string representing the complete state of the chain. Can be re-imported into a fresh/restarted instance of Anvil to reattain the same state.
anvil_loadState When given a hex string previously returned by anvil_dumpState, merges the contents into the current chain state. Will overwrite any colliding accounts/storage slots.
```
commands currently explicitly available in ape-foundry [https://github.com/apeworx/ape-foundry/blob/main/ape_foundry/provider.py](https://github.com/apeworx/ape-foundry/blob/main/ape_foundry/provider.py):
```
anvil_setBalance
anvil_impersonateAccount
anvil_stopImpersonatingAccount
anvil_setCode
anvil_reset
anvil_setNextBlockBaseFeePerGas
anvil_getAutomine
```
`anvil_reset` is currently available with `provider.reset_fork()`!!

**Comment by wakamex** [comment]
#576 implements basic dump and load from state, but 1) it was a lot more work than I thought and 2) it doesn't exactly reproduce the previous crash (I think it has to do with the RNG sequence)

**Comment by dpaiton** [comment]
handled by #1029
