### ISSUE TITLE
make local mount for contracts

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#557]
allow ape to compile from contracts inside docker
right now we have to have a local hyperdrive repo checked out and pointed to the right commit

**Comment by wakamex** [comment]
addressed by https://github.com/delvtech/infra/pull/18

**Comment by wakamex** [comment]
closed https://github.com/delvtech/infra/pull/18 as that implementation wasn't working

**Comment by dpaiton** [comment]
removed ape -- resolved
