### ISSUE TITLE
data-acquisition: design schema for PoolConfig, PoolInfo, Transactions and Agents

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#621]
- [x] PoolConfig
- [x] PoolInfo
- [x] Transactions
- [x] Agents

schema should resemble columns in json output produced by the current pipeline
Agents should store address & also their agent id

**Comment by slundqui** [comment]
Agents:
   Metadata? (not priority)
   Wallet information (use web3 to get balance of address, or get deltas from transaction receipts)

**Comment by slundqui** [comment]
User to agent mapping
