### ISSUE TITLE
data-acquisition: Add metadata table to map from "user" to multiple wallet addresses

### ISSUE THREAD

**Issue by slundqui** [delvtech/elf-simulations#635]
Wallet addresses table currently is indexed by wallet address. During bot competition, we ideally would like to keep track of wallets on a user level, where a user can have multiple wallets

**Comment by ryangoree** [comment]
What was the outcome here?

**Comment by dpaiton** [comment]
This was achieved via #654,  #707 , #708 , #710, #712
