### ISSUE TITLE
sim-server: spin up aws persistent devnet

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#644]
spin up devnet on ec2 and provide documentation for how to point evm-bots to it

**Comment by ryangoree** [comment]
@dpaiton @slundqui where is the documentation for this? Was this done using the compose app or was this a one off node?

**Comment by dpaiton** [comment]
https://www.notion.so/delv-tech/Bot-Trading-Documentation-538a7e77a34b4061904c47fbcc754c8d
