### ISSUE TITLE
Update logging to include a more extreme debugging level

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#76]
We primarily use `info` and `debug` for our two logging levels. However, there are some log statements that occur each trade, which could result in massive amounts of output and might not be desired for by a user trying to debug a problem. Let's add an additional level (name tbd... extreme debug? verbose debug? idk) that's below debug and is recommended to only be used when you're running a controlled setting with small numbers of trades, blocks per day, and days.

**Comment by slundqui** [comment]
Crash reporting uses critical logging level in https://github.com/delvtech/elf-simulations/pull/937
