### ISSUE TITLE
decide on data freshness in acquire_data.py

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#801]
as discussed in #785 we should decide on how fresh the data should be in acquire_data.py.

I'd argue the latest block is perfectly fine, at least for devnet uses:
- the reported block is after it's mined (transactions only exist in the mempool before being mined, and pretty sure anvil doesn't implement a mempool)
- [re-orgs](https://www.alchemy.com/overviews/what-is-a-reorg) don't happen on devnet, and I believe that's the only thing that affects block finality.

**Comment by dpaiton** [comment]
@wakamex is this issue resolved with the closed PR? I believe you and Sheng worked out a solution?

**Comment by wakamex** [comment]
resolved after some explicit testing in #845
