### ISSUE TITLE
request: further centralize configs

### ISSUE THREAD

**Issue by wakamex** [delvtech/elf-simulations#811]
currently I'm some config settings in 3 places, as seen in my [current workflow](https://github.com/wakamex/elf-simulations/blob/main/README.md)

that's `runner_config.py`, `acquire_data.py`, and in the `infra` repo.

the first two sound easier to combine, while creating a similar pattern with the infra repo would be nice. something like, if I set an environment variable (like my rpc port) of an agree-upon name, it would get picked up by both repos.

**Comment by dpaiton** [comment]
I think `.env` is the best route to share config across our different packages.

**Comment by wakamex** [comment]
it would also be nice to have a way to override config variables through code, like this <https://github.com/delvtech/elf-simulations/commit/12f1416e4c497c00dc176ec1bc91e0ecafa70e61>

i noticed `get_eth_bots_config` is run 3x in this flow, so the config params have to be passed in each time

**Comment by dpaiton** [comment]
@slundqui I think you're addressing this already with your agent0 refactor.

**Comment by wakamex** [comment]
yup, the higher level goal here is fully-programmatic access to configs, so we can run different experiments without changing code inside a package. then they can be installed without `-e` 🙌
