### ISSUE TITLE
agent0: Bots get current wallet positions (from chain? from db?) so it can pick up where it left off on bot process restart

### ISSUE THREAD

**Issue by slundqui** [delvtech/elf-simulations#850]
Currently, agent0 bots are assuming the process starts and never stops and breaks (lol). Ideally, we should be able to stop the bots process, potentially make logic updates, and bots pick up where they left off (as long as the number of bots and bot addresses stay the same). This involves getting bot positions on bot launch, either from the chain or from the db, so it can always keep track of it's positions within the bot.

**Comment by wakamex** [comment]
this is needed for basic analysis. anything that looks like this:

```
code_A
code_B
```

code_B doesn't have access to any positions that were created in code_A. this includes the default liquidity deployed in the devnet image by agent_0. so as it stands, I can't withdraw that liquidity.

we had a mostly working solution for restoring agent wallets in the unfinished dump_state code referenced here: https://github.com/delvtech/elf-simulations/issues/615#issuecomment-1619141834

**Comment by wakamex** [comment]
will review this week and see how much old code we can re-use, and what's left to do, at a minimum

**Comment by dpaiton** [comment]
FYI We solved this to some extent back when we used APE. The issue was #419 and the PR was #416

**Comment by dpaiton** [comment]
Would be nice to have both a "from db" solution and a "from chain" solution, since each solution has its pros/cons

**Comment by dpaiton** [comment]
Resolved from #894
