### ISSUE TITLE
Have flag in running elf simulations that disables develop mode for trading competition

### ISSUE THREAD

**Issue by slundqui** [delvtech/elf-simulations#899]

**Comment by slundqui** [comment]
Unfortunately, the fund agents script is doing smart contract calls directly to the chain, so the chain host can't control develop mode server side. We'll have to disable it on the client side in the code.

**Comment by dpaiton** [comment]
Here's the plan:
- @wakamex is going to make a discord bot that posts any time someone adds money via an RPC call
- @slundqui is going to set the "develop" default to FALSE and add a argument flag to run_agents script turn it to True
