### ISSUE TITLE
agent0: add crash reporting back in

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#918]
Trading competition V1 had a first-pass version of crash reporting, but we lost that functionality. We want to add it back in time for the second competition. The TODO is [here](https://github.com/delvtech/elf-simulations/blob/main/lib/agent0/agent0/hyperdrive/exec/trade_loop.py#L61)

**Comment by slundqui** [comment]
Closing with https://github.com/delvtech/elf-simulations/pull/937
