### ISSUE TITLE
docs: update documentation

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#920]
Tutorial-style workflow for running the bots (e.g. arb bot)
go over & clean up install & readme docs for setting up
fix doc links to be more accessible

**Comment by slundqui** [comment]
These 2 PRs need to be accounted for when updating docs
https://github.com/delvtech/elf-simulations/pull/908
https://github.com/delvtech/elf-simulations/pull/922

**Comment by slundqui** [comment]
Notion documentation is updated for running bots on the ec2 instance

**Comment by dpaiton** [comment]
Things to focus on from the build-a-bot workshop

- adding pyenv to shell (@wakamex mentioned this, not sure what it means)
- make more clear from the install which steps the average person can skip 
-
