### ISSUE TITLE
logging: optional parameter to `log_hyperdrive_crash_report` that defaults the `log_level` to `logging.CRITICAL`

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#967]
In the event that `trade_result.status == TradeStatus.FAIL`, but `halt_on_slippage == False` and `is_slippage == True`, then we want to call `log_hyperdrive_crash_report(trade_result, log_level=logging.WARNING)`, otherwise default is `logging.CRITICAL`

**Comment by slundqui** [comment]
https://github.com/delvtech/elf-simulations/pull/992
